### ISSUE TITLE
Suggestion: Warped Battery Pack / Warped Electrician's Pack

### ISSUE THREAD

**Issue by Grnkchi** [TGWeaver/CDDA-Sky-Islands#15]
A semi-persistent issue I have encountered in the new version is the fact that I have trouble getting storage batteries (of any size) to my island. Since we already have the lumberjack/scrapper/excavator bags, I propose something along the same lines for batteries and/or electronics, to make using the appliance systems a bit mlre viable by allowing easier transport of batteries and possibly power generation such as solar panels.

**Comment by TGWeaver** [comment]
I do think there need to be more types of special bags, especially as certain items like plastic chunks and other edge case materials don't have any condenser. That said, a massive one for storage batteries would let you effortlessly bring home like, a dozen in one go. That's probably more than intended.

For now, it should do to carry storage batteries and other heavy singular items with the warped hauler's harness. If you have a container sturdy and big enough (a large drum maybe?) you might be able to put multiple inside it and then carry the drum in the harness. But I am open to other ideas.
Maybe a parts bag that has a limited number of slots and is whitelisted for specific items like storage batteries and appliances?

**Comment by Grnkchi** [comment]
The limited-slot parts bag does sound like it would be more balanced than my initial suggestion and it would still keep with the 'enhance looting, don't replace it' aspect you mentioned before.

It's the best solution I can think of, at any rate.

**Comment by RDru** [comment]
You can put very large items into warped hauler's harness. Just checked and very large storage battery works.
