### ISSUE TITLE
Chance to spawn in "paintball field"

### ISSUE THREAD

**Issue by onura46** [TGWeaver/CDDA-Sky-Islands#17]
Since "field" is a part of "paintball field", any json with
```
"om_terrain": "field",
"om_terrain_match_type": "CONTAINS",
```
offers a very slight chance to spawn in a paintball field. It was funny and didn't cripple my run when it happened, but I assume the intention is to spawn in _field_ "fields".

My knowledge of this part of the json is a bit weak so I'm not sure how to fix it. The chance seems very low, anyway.

**Comment by onura46** [comment]
If this is intended, just ignore me 🙃

**Comment by TGWeaver** [comment]
It is possible to lock this strictly to fields, and I think you could do that by changing "CONTAINS" to "TYPE" (though I haven't tested), but personally, I actually enjoy being able to set down in farm fields, paintball fields, sports fields, and similar areas. Gives a little bit of unexpected variety, and it's a rare enough circumstance that I don't think it messes with balance too much.

**Comment by onura46** [comment]
> It is possible to lock this strictly to fields, and I think you could do that by changing "CONTAINS" to "TYPE" (though I haven't tested), but personally, I actually enjoy being able to set down in farm fields, paintball fields, sports fields, and similar areas. Gives a little bit of unexpected variety, and it's a rare enough circumstance that I don't think it messes with balance too much.

Agreed! Thought it was worth noting just in case, though.
