### ISSUE TITLE
Stuck in a death loop due to being unable to pick up the Salve of Forgiveness.

### ISSUE THREAD

**Issue by Eskjjlj** [TGWeaver/CDDA-Sky-Islands#18]
I got mauled by spiders, respawned on the island with all my limbs broken but I couldn't use the healing item because both of my arms were too damaged. I debug healed my arms and then I could pick it up to heal. 

Though after using it I remained blind.

Using : 
- cdda-windows-tiles-sounds-x64-2023-01-27-0622 
- This mod version as of Jan 25.

**Comment by TGWeaver** [comment]
It looks like the way healing is handled by code command was changed in the most recent CDDA patch. I'll have to run some tests to see how to square this with the existing healing code.

**Comment by Eskjjlj** [comment]
I see. I will use a previous version of CDDA to play the mod then 😄

**Comment by TGWeaver** [comment]
Update: Yes, definitely a bug related to CDDA's latest patch. It actually even breaks some vanilla parts of the game. A bug report has been submitted but I'm not sure when it will be patched, so for now your best bet is probably to use a CDDA version from a couple days ago.

Leaving this open for now so it can be re-addressed when CDDA is patched.

**Comment by jeugster** [comment]
Issue seems to be resolved in latest. Changelog suggests 2023-01-29-1619 fixed it. Seeing no broken parts after resurrection on 2023-1-30-1327

**Comment by TGWeaver** [comment]
Thanks jeugster, looks like this is working again, then.
