### ISSUE TITLE
[Bug] Severe Hypovolemic Shock (and potentially other conditions) causes repeated death loop

### ISSUE THREAD

**Issue by Terrorforge** [TGWeaver/CDDA-Sky-Islands#3]
I was just shot by a riot control turret, wasn't able to stop the bleeding, tried to get back to the portal before I died, and got killed by wasps. Once I spawned back in on the sky island, I had a drink of water, went to sleep, and proceeded to die in my sleep ten times. Upon waking, I'm still suffering from severe hypovolemic shock, and am continuing to die about once an hour.

So far this is the only thing that's actually killed me, but here's a couple of other things I've noticed that also don't get cleared by death and could cause similar problems:
- Infection
- Body temperature (freezing to death could be very problematic in winter starts)
- Poison
- Overdoses (including mutagen)

**Comment by TGWeaver** [comment]
This should be fixed with eff42d2. Let me know if it doesn't address ongoing problems.

**Comment by TGWeaver** [comment]
Okay, NOW it should be fixed. Took some testing and some of the cure statuses had hardcoded effects I didn't know about, but death should avoid MOST endless loops now. Let me know if this update helps.

**Comment by Terrorforge** [comment]
Yep, after dying one more time to trigger the new resets, the death loop seems to have stopped.

Just one thing: idk if you saw my comment, but instability should not be reset. That's the "vitamin" that tracks how likely you are to get bad mutations, resetting it will result in getting positive mutations basically all the time. The ones that can harm and potentially kill you are mutagen, mutagen_alpha, mutagen_batrachian, etc.

**Comment by TGWeaver** [comment]
The mutagen trees themselves can be lethal? I haven't really looked at mutation in some time so I wasn't aware how it had been changed. I'll have to dig into it more.

**Comment by Terrorforge** [comment]
I think you could always die of mutagen overdose, but now that mutations take place over time as a result of having certain vitamins in your system, the damaging side effects of an overdose can potentially last a really long time.

Here's the initial rework PR: https://github.com/CleverRaven/Cataclysm-DDA/pull/55233
A thing fixing instability: https://github.com/CleverRaven/Cataclysm-DDA/pull/58832
A pair of recent major fixes/tweaks:
https://github.com/CleverRaven/Cataclysm-DDA/pull/61036
https://github.com/CleverRaven/Cataclysm-DDA/pull/61684
