### ISSUE TITLE
[Bug] Crashes when starting up mod on mobile

### ISSUE THREAD

**Issue by Permahealer** [TGWeaver/CDDA-Sky-Islands#4]
Whenever i load up the world for character creation, it throws this error code and kicks me to the menu screen, i've seen some guy on reddit with the same problem but it was apparently solved by extracting the mod on his PC before transferring the files to their phone.
I can't do that but i really want to play the mod, it looks so fun 😭

Error 👇
  DEBUG    : Error: Json error: /storage/emulated/0/Android/data/com.cataclysmbnteam.cataclysmbn.experimental/files/data/mods/CDDA-Sky-Islands-main/EOCs.json:3:12: unrecognized JSON object

[
  {
    "type":
           ^
            "effect_on_condition",
    "id": "EOC_fieldwarp_statue",
	"//": "This EOC is triggered when activating the statue. It grabs a random location of a certain type (here a field), saves it to a global variable, and then triggers the actual tele

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : /home/runner/work/Cataclysm-BN/Cataclysm-BN/android/app/jni/src/main_menu.cpp
 LINE     : 871
 VERSION  : BN c336087

  {
    "type":i
           ^
            "effect_on_condition",
    "id": "EOC_fieldwarp_statue",
	"//": "This EOC is triggered when activating the statue. It grabs a random location of a certain type (here a field), saves it to a global variable, and then triggers the actual tele

 FUNCTION : bool main_menu::new_character_tab()
 FILE     : /home/runner/work/Cataclysm-BN/Cataclysm-BN/android/app/jni/src/main_menu.cpp
 LINE     : 871
 VERSION  : BN c336087

**Comment by TGWeaver** [comment]
You need to install a newer version of CDDA.

**Comment by Permahealer** [comment]
I'm already on the latest experimental version, didn't work :(

**Comment by TGWeaver** [comment]
No, you're playing Bright Nights. This mod is for DDA.
