### ISSUE TITLE
No longer working as of experimental build 2024-01-14-0524

### ISSUE THREAD

**Issue by Khrazlon** [TGWeaver/CDDA-Sky-Islands#52]
Using the latest 0.3.0 version of this, works fine up until I updated to an experimental version after the 2024-01-14-0524 build. No issues on the prior 0414 build. Unable to load world anymore. The error below:

```
DEBUG    : Error: Json error: data/mods/CDDA-Sky-Islands-main/EOCs.json:286:9: <color_white><color_cyan>invalid sub effect syntax: { "only_increase": true, "u_set_hp": 999 }</color>

      {
        "u_message": "Your body mends itself in the blink of an eye.  Underlying health issues may persist, but your structural integrity is restored."
<color_light_red>      },
</color>
       <color_cyan>▲▲▲</color>
      { "u_set_hp": 999, "only_increase": true },
      { "run_eocs": [ "EOC_healextras" ] }
</color>


 FUNCTION : load_game
 FILE     : D:\a\Cataclysm-DDA\Cataclysm-DDA\src\main_menu.cpp
 LINE     : 1038
 VERSION  : b89e0cd
```

The version/update in question:
https://github.com/CleverRaven/Cataclysm-DDA/releases/tag/cdda-experimental-2024-01-14-0524

**Comment by Standing-Storm** [comment]
I posted a patch in the pull requests

**Comment by TGWeaver** [comment]
Huge thanks to Standing Storm for this one. Merged the above PR, hopefully resolving this issue.
