### ISSUE TITLE
Balance: winter, cold & wind

### ISSUE THREAD

**Issue by Agoelia** [TGWeaver/CDDA-Sky-Islands#7]
I usually play with a randomized starting date, and 14 days season. This means there's a good chance I'll be meeting sub-zero temperatures not too far into the play through. 

The combination of lack of solid structures on the island, lack of firewood, hell even lack of stones to make a campfire ring, the amount of super strong, non stop wind, is just too tedious to deal with. 
It's not the difficulty so much that I mind, is how many extra clicks everything needs. 

Also candles basically become useless. 

Suggestion: add a separate scenario, which is identical except the sky island has a basement. It's an empty basement, also 3x3 chunks, with no light. It has more friendly temperatures, and no wind.

**Comment by TGWeaver** [comment]
I know this may seem like a flippant answer, but maybe just don't start in winter? Innawoods is another mod I would describe as already very difficult that turns near impossible in a deep winter start. Not every start is necessarily going to be viable, and given the nature of the mod, that may be unavoidable.

I may experiment with putting the island at a lower elevation, to avoid the extreme winds, but I can't be sure this will not cause other problems.

**Comment by Agoelia** [comment]
Well, you're not wrong. I also did some further thinking on the matter.
I guess the underlying issue is that there is no* way to "buy" a prefab building on the islands yet, or the materials needed to construct one. 
I know those features are planned and the issue will likely disappear on its own when those arrive. 

*It is perfectly possible to gather and bring back enough planks and nails to build a basic house, but it would likely take more time that it takes for winter to come, and it would be very tedious as well.
