### ISSUE TITLE
Suggestion: trader & procedural quests

### ISSUE THREAD

**Issue by Agoelia** [TGWeaver/CDDA-Sky-Islands#8]
Not everyone's cup of tea, so I would suggest making this a separate scenario. 

There's an unkillable trader on the island, he does not buy items. He initially only sells low-worth, high-volume or high-weight items: dirty, water, wood, stones, metal, very basic building materials, etc. Things that are extremely trivial to find in vanilla, but very tedious to bring back to the island in meaningful quantities. 

The only way to get ""money"" (hereafter called "points") is completing his procedural quests. The trader does not accept money or barter, only points. 

He always has [5] quests, and one can choose up to [2] before starting a raid. 
Coming back from a raid completes all quests you have satisfied the conditions for, rerolls all unchosen quests, and automatically fails the ones that could not be completed. So every quest has an effective timer of about 24 hours. 

Quests should have a good degree of randomization and could be: 
- find x amount of a certain item and bring it back (it gets deleted form your inventory when teleporting back to the island). This is already present in the game in a way.
- walk to a certain place (mall, lab, etc). Could be multiple places, like "visit 3x pharmacies and 2x gun stores". 
- walk to a specific place (noted on map)
- kill x amount of a certain enemy
- kill a specific enemy (noted on map)
- read a specific book / note, either a vanilla one or one specifically spawned for the quest
- butcher x amount of a certain animal
- gain x experience in a specific skill / proficiency 
- talk to x amount of npcs, or a specific npc

The value and type of reward should be know before accepting the mission 

Once in a while, the trader might have an exceptional reward for a slightly harder than usual mission: a welding rig, a solar panel, a refrigerator, a gun with some ammo, a skill book, 5 MREs, etc. 
These rewards should be randomly picked from a large list, so that players _cannot_ rely on the trader to get, for example, a metal stove early in the game. Every playthrough must be considerably different. 

Similarly, instead of an important item, the quest could unlock the possibility to buy some rarer (relatively speaking) materials: cotton sheets, kevlar ropes, strings, cement, clean water, etc. 
So in the late game, the trader will move form only selling hypercommon goods to low/medium rarity loot as well. 

Ideally, quests would have adaptive difficulty, Surviving many raids will increase the difficulty (and thus the value of the rewards), and the other way around too. 
Completing or failing the accepted quests should have a similar effect, but in a much less significant way. 

If the player manages to save a really large amount of points, they'll be able to afford upgrades to the sky islands: an extra chunk with a forest (for free wood), an extra chunk with already tilled terrain (for farming), an extra chunk with an empty house, an extra chunk with a semi-furnished garage / workshop, an extra chunk with a pond (for fishing and free water), a magical walk-in refrigerator, a solar farm for energy, etc.

**Comment by Khaligufzel** [comment]
I added something like this in my forked version. Check it out and let me know what you think!
I like your ideas about the missions. I think I will give it a go in my fork.

Here it is: https://github.com/Khaligufzel/CDDA-Sky-Islands

**Comment by TGWeaver** [comment]
Thanks for the suggestions. In fact, the upcoming version update will add kill missions and more ways to bring bulky goods home. While some other missions (item retrieval, visit x location) would be fun, currently there's no easy way I can find to randomize a core objective like that and so every variant would needs its own hand-written mission, so most missions will be target or total kills. Completing missions will earn shards, which you will be able to use to craft special items to help you along your way.
My intent with the balance here is to override the player's own looting as little as possible, and mostly just further facilitate it. To leave it more "vanilla" for that kind of exploration. Generally, I would rather give the player ways to bring home (for example) clay they already have to find than to give them a way to buy it at home.

The next version should be out in the next day or so, and while I anticipate there may be a lot of bugs with it, I hope it brings a stronger sense of balance and progression.

**Comment by Agoelia** [comment]
Hey Weaver, thanks for the answer. 
I really like the "enhancing looting" philosophy as opposed to skipping it by buying stuff. 

Maybe one can spend some form of currency to buy more time on the raid (more time to collect), or buy some single-use magical lockers that spawn in random locations. They spawn empty and can hold a good amount of stuff. When activated, they teleport themselves (and any content) back to the Island. 

The size of these lockers could scale with cost, starting with small ones the size of a small backpack, to huge ones that hold 4000L (same as a tile of dirt). 


And please don't even bother trying to make the next version retro-combatible, I'd be more than happy leaving my character behind if it means experimenting with new features. 

Looking forward to the next version!

**Comment by TGWeaver** [comment]
The new version is available. It should be compatible with old saves, because I've added a few safeguards to initialize any new variables.
Let me know if the new additions suit your needs!
