### ISSUE TITLE
Extract obelisk not spawning

### ISSUE THREAD

**Issue by Agoelia** [TGWeaver/CDDA-Sky-Islands#9]
I started a raid yesterday. 
This morning I updated to the most recent experimental (my installed version was about a week old). 
Then I loaded up the game, reached the extraction point, and there is no building and no obelisk. 

Is there a way to manually trigger the teleportation home? Or to manually spawn the obelisk?

**Comment by Willenbrink** [comment]
So your first option is obviously to die. That should always work :)

The mod also includes a spell to teleport you home. Normally that key is unbound but you can find it in "?" under "spellcasting". Haven't tried it myself but that should work (after spending some time on the ground, it is deactivated directly after arriving).

**Comment by TGWeaver** [comment]
I'm _pretty_ sure I squashed the bug causing this to happen in the last updated version, but a save that exists mid-raid between old versions may still have problems with it.
The spell will take you home, but if you ever need a direct line, you can use **Debug -> Game -> Run EOC -> EOC_statue_return**. This is the trigger that runs when you activate an exit obelisk.

**Comment by Agoelia** [comment]
Perfect, thank you. The spell worked just fine!
